variables:
  PACKAGE_PATH: /go/src/gitlab.com/enedi/fronius-netdata/fronius-netdata

stages:
  - build

build:
  stage: build
  image: docker:19
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/enedi/fronius-netdata/fronius-netdata .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/enedi/fronius-netdata/fronius-netdata
